Repository metaplex-foundation/metaplex-program-library, pull requests merged in 2022-11, with the labels that each got.

#603 Use ata for wallets and switch to v2
  token-metadata/Cargo.lock
  token-metadata/cli/Cargo.toml
  token-metadata/cli/src/main.rs
Labels: Cli Tools

#873 Trifle collections validation fix
  trifle/program/src/error.rs
  trifle/program/src/processor.rs
Labels: enhancement, NEEDS DEPLOY

#704 build: use solita api:gen to generate the client lib in the version workflow
  .github/actions/make-version-changes/action.yaml
  .github/actions/make-version-changes/script.js
  .github/workflows/apply-version-update.yml
  hydra/program/README.md
Labels: wip
